# frozen_string_literal: true

require "test_helper"

module Comms
  class TrainingMemoryPolicyTest < ActiveSupport::TestCase
    test "keeps Thumper canon and current facts in composition" do
      voice = { training_kind: "thumper_voice_canon", title: "Thumper Thumper Voice Canon", status: "indexed" }
      facts = {
        training_kind: "rag_canonical_resource",
        resource_key: "wizwiki_product_pricing_process",
        category: "wizwiki_product_process",
        title: "WIZWIKI product facts",
        status: "indexed"
      }

      assert_equal "voice_authority", TrainingMemoryPolicy.role_for(voice)
      assert_equal "fact_authority", TrainingMemoryPolicy.role_for(facts)
      assert TrainingMemoryPolicy.composition_eligible?(voice)
      assert TrainingMemoryPolicy.composition_eligible?(facts)
    end

    test "quarantines legacy raw memory and judge calibration" do
      legacy = { training_kind: "comms_playbook_memory", title: "Legacy thread", status: "indexed" }
      judge = { training_kind: "comms_dojo_judge_memory", title: "Judge memory", status: "indexed" }

      assert_equal "quarantined_memory", TrainingMemoryPolicy.role_for(legacy)
      assert_equal "judge_calibration", TrainingMemoryPolicy.role_for(judge)
      refute TrainingMemoryPolicy.composition_eligible?(legacy)
      refute TrainingMemoryPolicy.composition_eligible?(judge)
    end

    test "allows only explicitly approved conversation memory" do
      approved = {
        training_kind: "comms_playbook_memory",
        learning_status: "approved_positive",
        human_reviewed: true,
        title: "Approved thread",
        status: "indexed"
      }

      assert_equal "positive_example", TrainingMemoryPolicy.role_for(approved)
      assert TrainingMemoryPolicy.composition_eligible?(approved)
    end

    test "blocks autogenerated approval without human review" do
      autogenerated = {
        training_kind: "comms_playbook_memory",
        learning_status: "approved_positive",
        human_reviewed: false,
        title: "Legacy auto approval",
        status: "indexed"
      }

      assert_equal "quarantined_memory", TrainingMemoryPolicy.role_for(autogenerated)
      refute TrainingMemoryPolicy.composition_eligible?(autogenerated)
    end
  end
end
